### ISSUE TITLE
401 Error using repl

### ISSUE THREAD

**Issue by skiwheelr** [peterdemin/openai-cli#2]
```
➜  ~ openai repl --token <my api key>
Prompt: hello my name is
Traceback (most recent call last):
  File "/Users/mawagner/.pyenv/versions/3.9.4/bin/openai", line 8, in <module>
    sys.exit(cli())
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/openai_cli/cli.py", line 37, in repl
    print(client.generate_response(input("Prompt: "), model))
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/openai_cli/client.py", line 36, in generate_response
    response.raise_for_status()
  File "/Users/mawagner/.pyenv/versions/3.9.4/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.openai.com/v1/completions

```

**Comment by peterdemin** [comment]
I just checked, that repl works for me locally. I suspect something is wrong with the token.
